### PR TITLE
Docker compose

### PR DESCRIPTION
**Pull request by jbird526**
Addition of docker compose files and Readme update

### CODE REVIEW

**Review by jertel — APPROVED** [review]

**Comment by jbird526** [comment]
Thanks for moving the Docker Compose Readme content above Grafana. Better
formatting.

**Comment by jertel** [comment]
Welcome! Thanks for your contribution.

**Comment by jbird526** [comment]
Did want to bring up one issue. With the following file, maybe this is a
Docker Desktop for Mac thing, I have to remove the .template from the file
or the compose stack will not run. Dont have a Linux box or PC to test
alternate at the moment.

docker-compose.yaml.template

**Comment by jertel** [comment]
When I renamed that file to .template I also updated the documentation as follows:

image

This avoids having people change a version controlled file.

**Pull request merged**
