### PR TITLE
Cooldil - Customization of the tag, backfill missing per-minute/per-second data, customize max lookback for history collection.  Fixes for time precision of datapoints and historical day timestamp

### PR DESCRIPTION
**Pull request by cooldil**
This fixes and adds enhancements documented below:

FIXES:
- Time precision on datapoints submitted to the database for the second, minute and hour dataseries.  Prevents duplication of points if the data is pulled and stored again in the future.
- Addresses the UTC offset on the datapoint timestamp for the Day series during historical pulls.

ENHANCEMENTS:
- Allows for the customization of the "detailed" tag name and values via the tagName, tagValue_second, tagValue_minute, tagValue_hour and tagValue_day options in the config file.  Changes should be fully backwards compatible.
- Automatically backfills the second/minute data if the database is missing any datapoints.  Second data can be backfilled for a maximum of 3 hours while the minute data can be backfilled for a maximum of 7 days.
- Allows for the customization of the maximum number of history days that can be pulled via the maxHistoryDays config file entry.

Files modified:  vuegraf.py and README.md

### CODE REVIEW

**Comment by jertel** [comment]
I tried running this against my system (via Docker) and got this error:

```
2024-12-22 21:00:20.223049+00:00 | ERROR | Failed to record new usage data: (<class 'ValueError'>, ValueError("time data '2024-12-22T20:59:19.074638Z' does not match format '%Y-%m-%dT%H:%M:%S%z'"), <traceback object at 0x7ff0afa56840>)
Traceback (most recent call last):
  File "/opt/vuegraf/vuegraf.py", line 437, in <module>
    extractDataPoints(device, usageDataPoints)
  File "/opt/vuegraf/vuegraf.py", line 214, in extractDataPoints
    minuteHistoryStartTime, stopTimeMin, minuteHistoryEnabled = getLastDBTimeStamp(chanName, tagValue_minute, stopTime, stopTime, False)
                                                                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/vuegraf/vuegraf.py", line 166, in getLastDBTimeStamp
    dbLastRecordTime = datetime.datetime.strptime(timeStr, '%Y-%m-%dT%H:%M:%S%z').replace(tzinfo=datetime.timezone.utc)
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/_strptime.py", line 555, in _strptime_datetime
    tt, fraction, gmtoff_fraction = _strptime(data_string, format)
                                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/_strptime.py", line 333, in _strptime
    raise ValueError("time data %r does not match format %r" %
ValueError: time data '2024-12-22T20:59:19.074638Z' does not match format '%Y-%m-%dT%H:%M:%S%z'
```

I'm not sure why your dates are stored differently than mine, but the code will need to handle this gracefully.

**Comment by cooldil** [comment]
Date are not stored differently, it's just that your timestamps have microsecond precision (which is why you have duplication if data for the same timeframe is pulled again).  
Let me see if I can account for the use case where the timestamp for the last record in the database has microsecond precision....

**Comment by cooldil** [comment]
Fix made.  Validated against both InfluxDB v1 and v2 that the backfill code now accounts for timestamps with precision higher than a second....

**Comment by jertel** [comment]
Thanks, looks better:

image

I'll let it run for a day to see how the aggregates are handled.

**Comment by cooldil** [comment]
FYI.  I made one more minor fix.  The original code was using different timestamps for the "daily" values depending on if they were collected during normal runs or history runs (23:59:00 vs 23:59:59).  Code fixed to use the latter in both cases.

**Review by jertel — APPROVED** [review]

**Pull request merged**
